fichepfeBundle\Entity\Depot:
    type: entity
    table: depot
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        rapport:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        executable:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        date:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        poster:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
    lifecycleCallbacks: {  }
