fichepfeBundle\Entity\Soutenance:
    type: entity
    table: soutenance
    indexes:
        iduser:
            columns:
                - iduser
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        rapporteur:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        encadrant:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        presidentjury:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: presidentJury
        type:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        nometudiant:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        datesoutenance:
            type: date
            nullable: false
            column: dateSoutenance
        etat:
            type: boolean
            nullable: false
    manyToOne:
        iduser:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                iduser:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
