<?php

namespace fichepfeBundle\Repository;

/**
 * fichepfeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fichepfeRepository extends \Doctrine\ORM\EntityRepository
{

    public function searchNom($nom)
    {
        $q=$this->createQueryBuilder('m')
            ->where('m.nom LIKE :nom')
            ->setParameter(':nom',"%$nom%");
        return $q->getQuery()->getResult();
    }
}
